# Generated by Django 2.2.5 on 2020-01-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobDescription', models.TextField()),
                ('JobTitle', models.CharField(max_length=255)),
                ('URL', models.CharField(max_length=255)),
            ],
        ),
    ]
