# Generated by Django 2.2.5 on 2020-01-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userinput'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInput',
            new_name='UserInsert',
        ),
    ]
