# Generated by Django 2.2.5 on 2020-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200112_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinsert',
            name='CV',
            field=models.TextField(default='', max_length=1200),
        ),
    ]
